version: '3.2'
services:

  zookeeper:
    image: 'wurstmeister/zookeeper'
    ports:
      - '127.0.0.1:2181:2181'
    volumes:
      - 'zookeeper_data:/data/zookeeper'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'wurstmeister/kafka'
    ports:
      - '127.0.0.1:9092:9092'
    volumes:
      - 'kafka_data:/data/kafka'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - LOG4J_LOGGER_KAFKA_AUTHORIZER_LOGGER=DEBUG, authorizerAppender
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CREATE_TOPICS=url_metrics:2:1
    depends_on:
      - zookeeper

  db:
    image: postgres:13
    # configure
    # - logging, we want to see all statements. setting `log_min_duration_statement` causes to
    #   log to the same line (better than `log_statement` and `log_duration`)
    # - performance, memory settings assume you have 8+ GB of RAM
    command: >
      postgres
        -c log_destination=stderr
        -c logging_collector=off
        -c log_min_duration_statement=0
        -c max_wal_size=2GB
        -c debug_pretty_print=on
        -c log_checkpoints=on
        -c shared_buffers=1000MB
        -c effective_cache_size=2155MB
        -c checkpoint_completion_target=0.8
        -c work_mem=8MB
    ports:
      - 127.0.0.1:5434:5432
    environment:
      POSTGRES_USER: foo
      POSTGRES_PASSWORD: bar
      POSTGRES_DB: aiven_dev
    volumes:
      - 'pg_data:/var/lib/postgresql/data:delegated'
    expose:
      - 5432

volumes:
  zookeeper_data:
  kafka_data:
  pg_data:
