version: '3.2'
services:
  aiven_checker:
    build: ./
    environment:
      - HTTP_HOST=0.0.0.0
    ports:
     - "127.0.0.1:8000:8000"

  zookeeper:
    image: 'wurstmeister/zookeeper'
    ports:
      - '127.0.0.1:2181:2181'
    volumes:
      - 'zookeeper_data:/data/zookeeper'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'wurstmeister/kafka'
    ports:
      - '127.0.0.1:9092:9092'
    volumes:
      - 'kafka_data:/data/kafka'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - LOG4J_LOGGER_KAFKA_AUTHORIZER_LOGGER=DEBUG, authorizerAppender
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
  kafka_data:
