---
schedule:
  - url: 'http://httpbin.org/post?a=1'
    method: 'POST'
    body: {}
    headers:
      x-extra-header: '1'
  - url: 'http://httpbin.org/get?a=1'
  - url: 'https://rancher.zerotired.com/'
  - url: 'https://www.spiegel.de/'
